meta_product_name: "Hops!...I did it again.."
meta_title: "Hops!... I did it again - Help yourself being a better beer lover. "
meta_description: "Keep track of the beers you tasted"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards